### ISSUE TITLE
App crashes on loadup. 

### ISSUE THREAD

**Issue by ajinkya933** [shaqian/flutter_realtime_detection#5]
<img width="805" alt="Screenshot 2019-05-25 at 7 22 53 PM" src="https://user-images.githubusercontent.com/17012391/58370305-82b49880-7f22-11e9-9e66-1b9b916d4525.png">

when I press flutter run, The app gets loaded properly but on my android device it  says "flutter_realtime_detection keeps crashing". How do I resolve this ?

Error is:
```
2019-05-25 23:14:52.335 23090-23126/? E/SDK: [null:167] - SimpleHttpHelper RESPONSE failure:
    code=204
    result=
    url=http://sdk.api.kaffnet.com/v4/cut_v3.php
2019-05-25 23:14:52.336 23090-23142/? D/SDK: [null:122] - SimpleHttpHelper RESPONSE success:
    code=200
    result=success
    url=http://ad.api.kaffnet.com/adserver/v1/sdk/installreport/get?country=US&natural=0&gaid=5bcfe012-f456-4725-9145-e4cd09d57e4f&os_version=7.0&language=en&version=1&token=7701588d-ce77-f111-c7ec-2aae76ea7b4f&pkg_name=com.example.examplerealtime&sdk_version=4.3.1.0.4101.13&imei=&network_type=1&event=0&aid=de47178c80eaf91d&add_time=1558806292021&timestamp=1558806292021
2019-05-25 23:14:52.336 23090-23090/? E/SDK: [null:224] - 自然流量跳转失败:pkg=com.example.examplerealtime
2019-05-25 23:14:52.337 23090-23090/? D/SDK: [null:25] - -----------上传成功---------http://ad.api.kaffnet.com/adserver/v1/sdk/installreport/get
2019-05-25 23:14:52.346 923-923/? I/TelecomService: DefaultDialerCache: Refreshing default dialer for user 0: now com.android.dialer: DDC.oR@DEY
2019-05-25 23:14:52.382 4682-4682/? E/--ass--: --in---
2019-05-25 23:14:52.382 4682-4682/? E/--ass--: com.example.examplerealtime----android.widget.FrameLayout
2019-05-25 23:14:52.382 4682-4682/? E/--ass--: --in---
2019-05-25 23:14:52.382 4682-4682/? E/--ass--: com.example.examplerealtime----android.widget.FrameLayout
2019-05-25 23:14:52.502 4682-4682/? E/--ass--: --in---
2019-05-25 23:14:52.502 4682-4682/? E/--ass--: android----android.widget.TextView
2019-05-25 23:14:52.528 4682-4682/? E/--ass--: --in---
2019-05-25 23:14:52.528 4682-4682/? E/--ass--: android----android.widget.FrameLayout
2019-05-25 23:14:52.528 4682-4682/? E/--ass--: --in---
```

**Comment by shaqian** [comment]
Hi,
Can you try to launch the app from Android Studio?

**Comment by ajinkya933** [comment]
I tried launching from the Android store, here is my output:

<img width="1033" alt="Screenshot 2019-05-28 at 2 43 59 PM" src="https://user-images.githubusercontent.com/17012391/58466311-08b92500-8157-11e9-929d-03a12571a8a4.png">

The app is being installed successfully. But it keeps stopping on loading up:

Here is my Android log:
```
2019-05-28 15:11:04.545 1089-1089/com.example.examplerealtime23 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.examplerealtime23, PID: 1089
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.examplerealtime23-zKwxu8gYiFIV7eaxPpv_6g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.examplerealtime23-zKwxu8gYiFIV7eaxPpv_6g==/lib/arm, /data/app/com.example.examplerealtime23-zKwxu8gYiFIV7eaxPpv_6g==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:161)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:136)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6248)
        at android.app.ActivityThread.access$1200(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7076)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by shaqian** [comment]
The error is similar to
https://github.com/flutter/flutter/issues/18494
and
https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd

Can you please try the solutions suggested in the threads?

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
